import express from "express";
import { authenticate, authorize } from "../../middleware/auth.ts";
import dashboardRoutes from "./dashboardRoutes.ts";
import analyticsRoutes from "./analyticsRoutes.ts";
import studentBatchRoutes from "./studentBatchRoutes.ts";
import questionEventRoutes from "./questionEventRoutes.ts";
import testRoutes from "./testRoutes.ts";
import reportRoutes from "./reportRoutes.ts";
import verificationRoutes from "./verificationRoutes.ts";
import noticeMaterialRoutes from "./noticeMaterialRoutes.ts";
const router = express.Router();
router.use(authenticate, authorize(["TPO"]));
router.use(dashboardRoutes);
router.use(analyticsRoutes);
router.use(studentBatchRoutes);
router.use(questionEventRoutes);
router.use(testRoutes);
router.use(reportRoutes);
router.use(verificationRoutes);
router.use(noticeMaterialRoutes);
export default router;
