import express from "express";
import { authenticate, isAdmin } from "../../middleware/auth.ts";
import collegeTpoRoutes from "./collegeTpoRoutes.ts";
import batchOnboardingRoutes from "./batchOnboardingRoutes.ts";
import ecosystemAnalyticsRoutes from "./ecosystemAnalyticsRoutes.ts";
import globalModerationRoutes from "./globalModerationRoutes.ts";
import configurationRoutes from "./configurationRoutes.ts";
import communityAdminRoutes from "./communityAdminRoutes.ts";
import staffRoutes from "./staffRoutes.ts";
import contactInquiryRoutes from "./contactInquiryRoutes.ts";
const router = express.Router();
router.use(authenticate, isAdmin);
router.use(collegeTpoRoutes);
router.use(batchOnboardingRoutes);
router.use(ecosystemAnalyticsRoutes);
router.use(globalModerationRoutes);
router.use(configurationRoutes);
router.use(communityAdminRoutes);
router.use(staffRoutes);
router.use(contactInquiryRoutes);
export default router;
